version: "2.4"
networks:
  global:
    external: true
services:
  phi-config-service:
    env_file:
      - "./environment/poweredge.env"
    container_name: phi-config-service
    hostname: phi-config.vengeance.svc.cluster.local
      # build:
      # context: '.'
    # dockerfile: Dockerfile
    image: pysga1996/prv_repo:phi-config-service
    expose:
      - 80
    ports:
      - "8030:80"
    networks:
      - global
    volumes:
      - ./:/app
    restart: no
    logging:
      driver: json-file
    mem_limit: 512M
    mem_reservation: 128M
    cpus: 0.5