logging:
  level:
    root: INFO
  config: classpath:log4j-spring.xml
server:
  port: 80
  servlet:
    context-path: /phi-config-service
    encoding:
      charset: UTF-8
      enabled: true
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  forward-headers-strategy: framework
spring:
  application:
    name: phi-config-service
  security:
    user:
      name: ${CONFIG_USERNAME:}
      password: ${CONFIG_PASSWORD:}